# Generated by Django 4.1.4 on 2023-01-04 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestuarantsModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phoneNo', models.CharField(max_length=12)),
                ('possibleValues', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='registeredusers',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
